"""Initial

Revision ID: 7218198efdaa
Revises: 
Create Date: 2024-02-29 10:57:58.112929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7218198efdaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk__product'))
    )
    op.create_table('sale',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('sale_id', name=op.f('pk__sale'))
    )
    op.create_table('sale_item',
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk__sale_item_product_id_product')),
    sa.ForeignKeyConstraint(['sales_id'], ['sale.sale_id'], name=op.f('fk__sale_item_sales_id_sale')),
    sa.PrimaryKeyConstraint('sales_id', 'product_id', name=op.f('pk__sale_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_item')
    op.drop_table('sale')
    op.drop_table('product')
    # ### end Alembic commands ###
