name: CI

# Workflow should be executed on changing
# or new pull-request in main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # tests should run on each workflow run
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: docker://postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin_test
          POSTGRES_PASSWORD: admin_test
          POSTGRES_DB: sales

    steps:
      - uses: actions/checkout@v2

      - name: test
        uses: docker://snakepacker/python:3.10

        env:
          CI_SALES_PG_URL: postgresql://admin_test:admin_test@postgres/sales
        with:
          args: /bin/bash -c "apt-get update && apt-get install -y python3-pip && pip install -U '.[dev]' && pylama && wait-for-port postgres:5432 && pytest -vv --cov=analyzer --cov-report=term-missing tests"

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/head/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions//checkout@v2
      - name: sdist
        uses: docker://snakepacker//python:3.10
        with:
          args: make sdist

      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          repository: temaxuck/sales-tracking-api
          target: api
          tags: 0.0.1, latest
